# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  chat:
    image: chat
    build:
      context: .
      dockerfile: Chat/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 6379:6379
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
